almacenes_por_seccion_v,  CREATE VIEW almacenes_por_seccion_v AS  SELECT a.cod_seccion, b.*  FROM almacenes_por_seccion a  INNER JOIN almacenes b ON a.cod_almacen = b.cod_almacen
articulos_imagenes_v,CREATE VIEW dbo.articulos_imagenes_v  AS  SELECT     TOP 100 PERCENT *  FROM         dbo.articulos_imagenes ai  WHERE     (tipo = N'imagen')  ORDER BY producto, orden  
asignados_por_tarea,CREATE VIEW dbo.asignados_por_tarea  AS  SELECT     TOP 100 PERCENT dbo.Orden_fabricacion.nro_plan AS Lote, dbo.Tareas_cabecera.nro_orden_fabricacion, dbo.Tareas_cabecera.nro_tarea,                         dbo.Orden_fabricacion.cod_articulo, dbo.Orden_fabr
banco_propio_v,  CREATE VIEW [dbo].[banco_propio_v] AS   SELECT b.nombre, bp.*   FROM banco b   INNER JOIN banco_propio bp ON b.cod_banco = bp.cod_banco
caja_v,  CREATE VIEW caja_v AS   SELECT  c.cod_caja, c.cod_duenio, c.cod_caja_padre, c.nombre, c.fecha_limite, c.dias_cierre, ISNULL(c.importe_efectivo, 0) AS importe_efectivo, c.importe_descubierto,       c.importe_maximo, c.cod_imputacion, c.caja_banco, c.anula
cajas_posibles_transferencia_interna_v,  CREATE VIEW [dbo].[cajas_posibles_transferencia_interna_v] AS   SELECT cpti.*, c1.nombre nombre_caja_salida, c2.nombre nombre_caja_entrada   FROM cajas_posibles_transferencia_interna cpti   INNER JOIN caja c1 ON cpti.cod_caja_salida = c1.cod_caja   INNER
cajas_resumen,  CREATE VIEW cajas_resumen AS     SELECT    fecha,   (    CASE    WHEN (SELECT 1 FROM caja_saldos_diarios WHERE caja_fecha = fecha) = 1 THEN 'S'    ELSE 'N'    END   ) caja_cerrada,   SUM(cd_importe_1) cd_importe_1,   SUM(cd_importe_2) cd_importe_2,   SUM
cheque_v,CREATE VIEW [dbo].[cheque_v] AS   SELECT c.*, b.nombre as banco_nombre,   DATEDIFF(dd, GETDATE(), c.fecha_vencimiento) as dias_vencimiento   FROM cheque c   LEFT JOIN banco b ON b.cod_banco = c.cod_banco    
chequera_v,CREATE VIEW [dbo].[chequera_v] AS  SELECT c.*, d.cod_chequera_d, d.numero, d.utilizado, cb.nombre_cuenta  FROM chequera_c c  INNER JOIN chequera_d d ON c.cod_chequera = d.cod_chequera  INNER JOIN cuenta_bancaria cb ON c.cod_cuenta_bancaria = cb.cod_cuenta_
cheques_propios_v,CREATE VIEW cheques_propios_v AS   SELECT  c.cod_cheque, c.empresa, c.numero, banco.nombre AS banco_nombre, c.importe, c.fecha_vencimiento, p.cod_prov, p.razon_social,       c.librador_nombre, c.dias_vencimiento AS dias, c.esperando_en_banco, c.fecha_credi
cheques_rechazados_v,    CREATE VIEW cheques_rechazados_v AS   SELECT fecha_documento fecha, c.fecha_vencimiento, c.empresa, cli.cod_cli, cli.razon_social cliente_razon_social, p.cod_prov, p.razon_social proveedor_razon_social,   c.librador_nombre, b.nombre banco_nombre, c.num
clientes_v,      CREATE VIEW clientes_v AS   SELECT (o.nombres + ' ' + o.apellido) nombre_vendedor, debe.fecha_debe, debe.importe_pendiente_debe, haber.fecha_haber, haber.importe_pendiente_haber, a.saldo,     plazos.dias_promedio_pago, ISNULL(total_cheques.total_cheq
colores_por_articulo_v, --View para no hacer un JOIN en el mapper  CREATE  VIEW colores_por_articulo_v AS  SELECT   a.denom_articulo,   cpa.cod_articulo,   cpa.cod_color_articulo,   cpa.denom_color,   cpa.cod_variante,   cpa.corte,   cpa.vigente,   cpa.fecha_de_baja,   cpa.denom
compras_pendientes,CREATE VIEW dbo.compras_pendientes  AS  SELECT     TOP 100 PERCENT dbo.Ordenes_compra_detalle.cod_material, dbo.Ordenes_compra_detalle.cod_color,                         SUM(dbo.Ordenes_compra_detalle.cantidad_pendiente) AS pendiente  FROM         dbo.Orde
compras_vw,CREATE VIEW dbo.compras_vw  AS  SELECT     TOP 100 PERCENT dbo.compras_cabecera.empresa, dbo.compras_cabecera.fecha, dbo.compras_cabecera.fecha_periodo_fiscal, dbo.compras_cabecera.tipo_doc,                         dbo.compras_cabecera.letra, dbo.compras_c
consumos_comprometidos_v,CREATE VIEW dbo.consumos_comprometidos_v  AS  SELECT     dbo.tareas_incumplidas_v.nro_plan, dbo.tareas_incumplidas_v.nro_orden_fabricacion, dbo.tareas_incumplidas_v.nro_tarea,                         dbo.tareas_incumplidas_v.cantidad, dbo.patrones_v.cod_ar
costo_factura_total_v,CREATE VIEW dbo.costo_factura_total_v  AS  SELECT     TOP 100 PERCENT dbo.documentos_cantidades.fecha, dbo.documentos_cantidades.empresa, dbo.documentos_cantidades.punto_venta,                         dbo.documentos_cantidades.tipo_docum, dbo.documentos_ca
costo_mp_factura_24meses_v,CREATE VIEW dbo.costo_mp_factura_24meses_v  AS  SELECT     TOP 100 PERCENT dbo.documentos_cantidades.fecha, dbo.documentos_cantidades.empresa, dbo.documentos_cantidades.punto_venta,                         dbo.documentos_cantidades.tipo_docum, dbo.document
costo_mp_factura_v,CREATE VIEW dbo.costo_mp_factura_v  AS  SELECT     TOP 100 PERCENT dbo.documentos_cantidades.fecha, dbo.documentos_cantidades.empresa, dbo.documentos_cantidades.punto_venta,                         dbo.documentos_cantidades.tipo_docum, dbo.documentos_canti
costo_mp_producto_detalle_v,CREATE VIEW dbo.costo_mp_producto_detalle_v  AS  SELECT     dbo.patrones_vigentes_v.cod_articulo, dbo.patrones_vigentes_v.denom_articulo, dbo.patrones_vigentes_v.cod_color_articulo,                         dbo.patrones_vigentes_v.tipo_patron, dbo.patrones_
costo_mp_producto_V,CREATE VIEW dbo.costo_mp_producto_V  AS  SELECT     cod_articulo, denom_articulo, cod_color_articulo, SUM(Costo) AS Costo, cod_linea  FROM         dbo.costo_mp_producto_detalle_v  GROUP BY cod_articulo, denom_articulo, cod_color_articulo, cod_linea  
costo_mp_semielaborado_detalle_v,CREATE VIEW dbo.costo_mp_semielaborado_detalle_v  AS  SELECT     dbo.patrones_se_vigentes_v.cod_articulo, dbo.patrones_se_vigentes_v.denom_articulo, dbo.patrones_se_vigentes_v.cod_color_articulo,                         dbo.patrones_se_vigentes_v.tipo_patr
costo_producto_total_V,CREATE VIEW dbo.costo_producto_total_V  AS  SELECT     costo_agrupado.cod_linea AS cod_linea, costo_agrupado.cod_articulo AS cod_articulo, costo_agrupado.denom_articulo AS denom_articulo,                         costo_agrupado.cod_color_articulo AS cod_col
costos_fijos_periodo_v,CREATE VIEW dbo.costos_fijos_periodo_v  AS  SELECT     dbo.costos_fijos_c.nro_periodo, dbo.costos_fijos_d.cod_linea,                         dbo.costos_fijos_c.costo_estructura * dbo.costos_fijos_d.porcentaje_periodo / 100 / dbo.costos_fijos_d.cantidad_pro
costos_fijos_periodo_vig_v,CREATE VIEW dbo.costos_fijos_periodo_vig_v  AS  SELECT     dbo.costos_fijos_c.nro_periodo, dbo.costos_fijos_d.cod_linea,                         dbo.costos_fijos_c.costo_estructura * dbo.costos_fijos_d.porcentaje_periodo / 100 / dbo.costos_fijos_d.cantidad
cuenta_corriente_historica,  CREATE VIEW [dbo].[cuenta_corriente_historica] AS   SELECT TOP 100 PERCENT r.empresa empresa, 1 punto_venta, 'REC' tipo_docum, '' tipo_docum_2, r.nro_recibo numero, 'R' letra, NULL nro_comprobante,           r.cod_cliente cod_cliente, r.fecha_documento f
cuenta_corriente_historica_proveedor,/*  ((CASE tipo_doc      WHEN 'NCR' THEN (-1)     ELSE (1)    END) * total_doc) total_documento  empresa, cod_prov, tipo_doc, nro_doc, fecha, total_doc importe_debe (FAC NDB), total_doc importe_haber (NCR OP)*/  CREATE VIEW dbo.cuenta_corriente_historica_p
cuenta_corriente_historica_proveedor_v,CREATE VIEW [dbo].[cuenta_corriente_historica_proveedor_v] AS   SELECT    dp.empresa, dp.punto_venta, dp.tipo_docum, dp.nro_documento, dp.letra, dp.cod_proveedor, dbo.relativeDate(dp.fecha,'today',0) fecha, dp.observaciones, (case when dp.tipo_docum = 'NCR
despachos_d_v,CREATE VIEW despachos_d_v AS   SELECT   d.nro_despacho nro_despacho,   d.nro_item nro_item,   d.empresa empresa,   d.anulado anulado,   cli.razon_social razon_social,   c.cod_cliente cod_cliente,   c.cod_sucursal cod_sucursal,   c.cod_ecommerce_order cod_e
despachos_v,  CREATE VIEW despachos_v AS   SELECT   d.nro_despacho_nro nro_despacho,   d.nro_item_despacho nro_item,   d.cod_empresa_despacho empresa,   d.cod_cli cod_cliente,   d.cod_suc_cli cod_sucursal,   d.nro_pedido_nro nro_pedido,   d.anulado anulado,   d.pendie
documento_proveedor,  CREATE VIEW [dbo].[documento_proveedor] AS   SELECT     /* campos de DocumentoProveedor */     id, empresa, punto_venta, tipo_docum, nro_documento, letra, cod_proveedor, operacion_tipo, fecha,     neto_gravado, neto_no_gravado, importe_total, importe_pen
documento_proveedor_aplicacion_debe_v,  CREATE VIEW [dbo].[documento_proveedor_aplicacion_debe_v] AS   SELECT * FROM documento_proveedor_aplicacion_v WHERE tipo_docum = 'FAC' OR tipo_docum = 'NDB'
documento_proveedor_aplicacion_haber_v,  CREATE VIEW [dbo].[documento_proveedor_aplicacion_haber_v] AS   SELECT * FROM documento_proveedor_aplicacion_v WHERE tipo_docum = 'OP' OR tipo_docum = 'NCR' OR tipo_docum = 'REN'
documento_proveedor_aplicacion_v,  CREATE VIEW [dbo].[documento_proveedor_aplicacion_v] AS   SELECT cod_documento_proveedor AS id, empresa, punto_venta, tipo_docum, nro_documento, letra,     factura_gastos, cod_proveedor, fecha, importe_total, importe_pendiente   FROM dbo.documento_provee
documento_proveedor_h_v,    CREATE VIEW [dbo].[documento_proveedor_h_v] AS   SELECT    h.id, h.empresa, h.cod_madre, h.cod_cancel, h.tipo_docum_cancel, h.importe, h.cod_usuario, h.fecha_alta,    dad.fecha AS fecha_debe, dah.fecha AS fecha_haber, dad.cod_proveedor, dad.factura_gas
documentos,    CREATE VIEW [dbo].[documentos] AS   SELECT     empresa, punto_venta, tipo_docum, numero, letra, nro_comprobante, anulado, tipo_docum_2, cod_cliente, cod_sucursal, cod_usuario,     cancel_nro_documento, causa, CAST(observaciones AS VARCHAR(8000)) observ
documentos_aplicacion_debe_v,   CREATE VIEW documentos_aplicacion_debe_v AS    SELECT empresa, punto_venta, tipo_docum, nro_documento, letra, nro_comprobante, cod_cliente, fecha, importe_total, importe_pendiente    FROM documentos_aplicacion_v    WHERE (tipo_docum = 'FAC') OR (tipo_do
documentos_aplicacion_haber_v,   CREATE VIEW documentos_aplicacion_haber_v AS    SELECT empresa, punto_venta, tipo_docum, nro_documento, letra, nro_comprobante, cod_cliente, fecha, importe_total, importe_pendiente    FROM documentos_aplicacion_v    WHERE (tipo_docum = 'REC') OR (tipo_d
documentos_aplicacion_v,   CREATE VIEW documentos_aplicacion_v AS    SELECT empresa, punto_venta, tipo_docum, nro_documento, letra, nro_comprobante, cod_cliente, fecha_documento AS fecha, importe_total, importe_pendiente    FROM documentos_c    WHERE anulado = 'N'    UNION ALL   
documentos_cantidades,  CREATE VIEW documentos_cantidades AS   SELECT c.fecha fecha, c.cod_cliente cod_cliente, a.*  FROM (   (    SELECT     empresa empresa, punto_venta punto_venta, tipo_docum tipo_docum, nro_documento nro_documento, letra letra_documento,     NULL nro_remito
documentos_d_v,CREATE VIEW documentos_d_v AS   SELECT   d.*,   c.anulado,   c.cod_cliente  FROM   documentos_d d  LEFT JOIN documentos_c c ON d.empresa = c.empresa AND c.punto_venta = d.punto_venta AND d.tipo_docum = c.tipo_docum AND d.nro_documento = c.nro_documento AND
documentos_h_v,   CREATE VIEW documentos_h_v AS    SELECT h.*, dad.fecha fecha_debe, dah.fecha fecha_haber, dad.cod_cliente    FROM documentos_h h    INNER JOIN documentos dad ON     h.empresa = dad.empresa AND     h.madre_punto_venta = dad.punto_venta AND     h.madre_ti
documentos_rentabilidad,CREATE VIEW dbo.documentos_rentabilidad  AS  SELECT     TOP 100 PERCENT dbo.documentos.empresa, dbo.documentos.punto_venta, dbo.documentos.tipo_docum, dbo.documentos.numero,                         dbo.documentos.letra, dbo.documentos.anulado, dbo.document
documentos_vendedor,  CREATE VIEW [dbo].[documentos_vendedor] AS   SELECT     d.*, c.cod_vendedor, c.razon_social   FROM documentos d   LEFT JOIN clientes c ON d.cod_cliente = c.cod_cli  
ecomexperts_articulos_update_v,CREATE VIEW dbo.ecomexperts_articulos_update_v  AS  SELECT     TOP 100 PERCENT dbo.colores_por_articulo.ml_reference AS sku, dbo.colores_por_articulo.ml_name AS titulo, '' AS garantia, 21 AS impuesto,                         'default' AS precio_titulo1, db
ecommerce_colores_por_articulo_v,  CREATE VIEW ecommerce_colores_por_articulo_v AS    SELECT   c.cod_articulo cod_articulo,   c.cod_color_articulo cod_color_articulo,   c.fechaUltimaMod fecha_ultima_mod,   c.categoria_usuario categoria_usuario,     c.ecommerce_existe ecommerce_existe,   c
ecommerce_orders_v,CREATE VIEW ecommerce_orders_v AS    SELECT o.*, c.firstname, c.lastname, c.cod_usergroup cod_usergroup, u.nombre nombre_usergroup  FROM ecommerce_orders o  LEFT JOIN ecommerce_customers c ON o.cod_customer = c.cod_customer  LEFT JOIN ecommerce_usergroups 
egreso_de_fondos_v,CREATE VIEW [dbo].[egreso_de_fondos_v] AS   SELECT op.nro_orden_de_pago numero, op.empresa, (case when op.cod_proveedor is null then op.beneficiario else ('[' + cast(p.cod_prov AS VARCHAR) + '] ' + p.razon_social) end) de_para,    (SELECT ISNULL(SUM(e1.imp
egresos_compras_gastos_vw,  CREATE   view    egresos_compras_gastos_vw as    select  * from(SELECT top 100 percent  dbo.compras_cabecera.empresa, dbo.compras_cabecera.fecha, dbo.compras_cabecera.fecha_periodo_fiscal, dbo.compras_cabecera.tipo_doc,                         dbo.compra
egresos_ff_vw,CREATE VIEW dbo.egresos_ff  AS  SELECT     dbo.gastos_rendicion.empresa, dbo.gastos_rendicion.sucursal_empresa, dbo.gastos_rendicion.gasto_fecha AS fecha,                         dbo.gastos_rendicion.operacion_tipo AS tipo, dbo.ordenes_de_pago.tipo_docum A
egresos_op_vw,CREATE VIEW dbo.egresos_op_vw  AS  SELECT     empresa, sucursal_empresa, fecha_orden_pago AS fecha, operacion_tipo AS tipo, tipo_docum AS docum, orden_pago_nro AS op_nro, cod_prov,                         importe_a_pagar AS importe, imput_obligacion_paga A
egresos_vw,CREATE VIEW dbo.egresos_vw  AS  SELECT     dbo.gastos_rendicion.empresa, dbo.gastos_rendicion.sucursal_empresa, dbo.gastos_rendicion.gasto_fecha AS fecha,                         dbo.gastos_rendicion.operacion_tipo AS tipo, dbo.ordenes_de_pago.tipo_docum A
facturacion_cantidades_por_articulo_v,CREATE VIEW dbo.facturacion_cantidades_por_articulo_v  AS  SELECT     dbo.documentos_cantidades.fecha, dbo.documentos_cantidades.empresa, dbo.documentos_cantidades.cod_almacen,                         dbo.documentos_cantidades.cod_articulo, dbo.articulos.d
facturas_con_saldo_pendientexxx,CREATE VIEW dbo.facturas_con_saldo_pendiente  AS  SELECT     empresa, tipo_docum, factura_nro, letra_factura, cod_cli, saldo_pendiente, documento_fecha, pagado_total, desactivado_aplicado, grado  FROM         dbo.docum_clientes_cabecera  WHERE     (saldo_p
facturas_detalle, CREATE  VIEW dbo.facturas_detalle  AS  SELECT     TOP 100 PERCENT dbo.Despachos_detalle.nro_despacho_nro AS nro_despacho, dbo.Despachos_detalle.nro_item_despacho AS nro_item,                         dbo.Despachos_detalle.cod_empresa_despacho AS empresa, d
fasonier_v,CREATE VIEW dbo.fasonier_v AS  SELECT P.*, o.cod_operador ,o.tipo_operador FROM operadores o  INNER JOIN proveedores_datos p ON o.cod_proveedor = p.cod_prov  
ficha_tecnica_patrones_d,CREATE VIEW dbo.ficha_tecnica_patrones_d  AS  SELECT     p.cod_articulo, p.cod_color_articulo, p.version, p.nro_item, p.cod_pieza, p.cod_material, p.cod_color_material, p.cod_seccion, p.fecha_alta, p.item_nuevo,                         p.consumo_par, p.con
fichajes_v,  CREATE VIEW fichajes_v AS  SELECT   r.clave_tabla, r.legajo_nro, r.movimiento_tipo, r.fecha, r.entrada_horario, r.salida_horario, r.con_anomalias, r.ubicacion_tipo, r.ubicacion_confirmada,   r.diferencia_entrada, r.diferencia_salida, p.cod_personal, p.se
filas_asientos_contables_v,CREATE VIEW dbo.filas_asientos_contables_v  AS  SELECT     TOP 100 PERCENT c.cod_asiento, c.empresa, c.nombre AS asunto, dbo.round(c.importe) AS importe, c.cod_ejercicio, c.fecha_asiento, d.numero_fila,                         d.cod_imputacion, pc.denomina
gastos_vw,CREATE VIEW dbo.gastos_vw  AS  SELECT     TOP 100 PERCENT empresa, gasto_fecha AS fecha, fecha_rendicion AS fecha_periodo_fiscal, comprobante_tipo AS tipo_doc, '' AS letra, comprobante_nro AS nro_doc,                         '' AS cod_prov, cuit_proveedor 
gestion_proveedores,  CREATE VIEW gestion_proveedores AS   SELECT p.cod_prov, p.razon_social, p.cuit, p.imputacion_especifica, i.denominacion, p.anulado, p.observaciones_gestion, a.saldo, total_cheques   FROM dbo.proveedores_datos AS p    LEFT JOIN (    SELECT p.cod_prov, ISN
gestion_proveedores_1,  CREATE VIEW gestion_proveedores_1 AS   SELECT p.cod_prov, p.razon_social, p.cuit, p.imputacion_especifica, i.denominacion, p.anulado, p.observaciones_gestion, a.saldo   FROM dbo.proveedores_datos AS p    LEFT JOIN (    SELECT p.cod_prov, ISNULL(SUM((CASE
gestion_proveedores_2,  CREATE VIEW gestion_proveedores_2 AS   SELECT p.cod_prov, p.razon_social, p.cuit, p.imputacion_especifica, i.denominacion, p.anulado, p.observaciones_gestion, a.saldo   FROM dbo.proveedores_datos AS p    LEFT JOIN (    SELECT p.cod_prov, ISNULL(SUM((CASE
importe_por_operacion_d_v,   CREATE VIEW importe_por_operacion_d_v AS    SELECT d.*, c.tipo_transferencia, c.cod_caja, c.fecha_caja, c.fecha_alta    FROM importe_por_operacion_d d    INNER JOIN importe_por_operacion_c c ON d.cod_importe_operacion = c.cod_importe_operacion
importes_op_acumulado_mes,    CREATE VIEW [dbo].[importes_op_acumulado_mes] AS   SELECT p.cod_prov cod_proveedor, SUM(ISNULL(op.importe_sujeto_ret, 0)) importe_acumulado_mes, SUM(ISNULL(re.importe_retenido, 0)) importe_retenido_mes   FROM proveedores_datos p    LEFT JOIN orden_de_p
indicadores_por_rol_v,  CREATE VIEW indicadores_por_rol_v AS   SELECT TOP 100 PERCENT ixr.cod_indicador, i.nombre nombre_indicador, r.*   FROM indicadores_por_rol ixr   INNER JOIN roles r ON ixr.cod_rol = r.cod_rol   INNER JOIN indicadores i ON i.cod_indicador = ixr.cod_indicad
ingresos_v,CREATE VIEW dbo.ingresos_v  AS  SELECT     fecha_alta, empresa, tipo_docum, nro_documento, cod_cliente, operacion_tipo, importe_1, importe_2, importe_3, importe_4, importe_5,                         ingreso_bancario_importe, importe_6, importe_total, plazo
koi_ticket_v,  CREATE VIEW koi_ticket_v AS   SELECT TOP 100 PERCENT * FROM (    -- 1. Los que tienen fecha de resolución (con o sin responsable)    SELECT *, 1 orden1, fecha_estimada_resolucion orden2, NULL orden3 FROM koi_ticket    WHERE anulado = 'N' AND fecha_estima
lineas_productos, -- Crear la vista llamada 'lineas' en la base de datos 'desarrollo'  CREATE VIEW lineas_productos AS  SELECT       cod_linea,      denom_linea,      origen,      lanzamiento_inicial,      estado_de_linea,      fecha_de_baja,      anulado,      material,  
listado_clientes_v,CREATE VIEW listado_clientes_v AS   SELECT c.cod_cli cod_cliente, c.razon_social, c.denom_fantasia, c.cuit, c.cod_vendedor,     sc.telefono_1, sc.telefono_2, c.email email_cliente, sc.email email_sucursal,     pa.cod_pais, pr.cod_provincia, pr.denom_provin
listado_proveedores_v,  CREATE VIEW dbo.listado_proveedores_v AS   SELECT  p.*, pr.denom_provincia, l.denom_localidad   FROM  proveedores_v p      LEFT OUTER JOIN provincias pr ON pr.cod_provincia = p.provincia      LEFT OUTER JOIN localidades l ON l.cod_localidad = p.localidad
Marcas, -- Crear la vista llamada 'marcas' en la base de datos 'encinitas', que apunta a la tabla de 'spiral'  CREATE VIEW Marcas AS  SELECT       cod_marca,      cod_cliente,      denom_marca,      anulado,      fecha_ultima_modificacion,      autor_ultima_modif
materiales_preferentes_v,CREATE VIEW dbo.materiales_preferentes_v  AS  SELECT     TOP 100 PERCENT dbo.materiales.cod_material, dbo.Materias_primas.cod_color, dbo.materiales.denom_material AS Material,                         dbo.Proveedores_materias_primas.cod_proveedor, dbo.prove
materiales_v,CREATE VIEW materiales_v AS   SELECT m.*, a.cod_articulo, a.naturaleza   FROM materiales m   LEFT OUTER JOIN articulos a ON m.cod_material = a.cod_material  
materias_primas_v,  CREATE VIEW materias_primas_v AS   SELECT mp.*, cmp.denom_color, cmp.abrev_color   FROM Materias_primas mp   INNER JOIN Colores_materias_primas cmp ON mp.cod_color = cmp.cod_color
movimientos_caja_v,  CREATE VIEW [dbo].[movimientos_caja_v] AS   SELECT 'I' tipo, 'REC' tipo_documento, r.nro_recibo numero, (case when r.cod_cliente is null then r.recibido_de else c.razon_social end) de, 'SPIRAL SHOES S.A.' para,    (SELECT ISNULL(SUM(e1.importe), 0)    FR
movimientos_caja_v_anul,CREATE VIEW movimientos_caja_v_anul AS     SELECT 'E' tipo, 'REC' tipo_documento, r.nro_recibo numero, (case when r.cod_cliente is null then r.recibido_de else c.razon_social end) de, 'SPIRAL SHOES S.A.' para,    (SELECT ISNULL(SUM(e1.importe), 0)    FROM 
movimientos_caja_v_chq,CREATE VIEW movimientos_caja_v_chq AS     SELECT * FROM (   SELECT 'E' tipo, 'DC' tipo_documento, dc.cod_acreditar_debitar_cheque numero,    (SELECT '[' + cast(caja.cod_caja AS VARCHAR) + '] ' + caja.nombre    FROM acreditar_debitar_cheque_d dc1    INNER J
movimientos_caja_v_chq,CREATE VIEW movimientos_caja_v_chq AS     SELECT * FROM (   SELECT 'E' tipo, 'DC' tipo_documento, dc.cod_acreditar_debitar_cheque numero,    (SELECT '[' + cast(caja.cod_caja AS VARCHAR) + '] ' + caja.nombre    FROM acreditar_debitar_cheque_d dc1    INNER J
movimientos_caja_v_noanul,    CREATE VIEW movimientos_caja_v_noanul AS     SELECT 'I' tipo, 'REC' tipo_documento, r.nro_recibo numero, (case when r.cod_cliente is null then r.recibido_de else c.razon_social end) de, 'SPIRAL SHOES S.A.' para,    (SELECT ISNULL(SUM(e1.importe), 0)   
movimientos_stock_mp_v,  ------------------------------------------------------------------------ MOVIMIENTOS VIEW ------------------------------------------------------------------------------------------      CREATE VIEW dbo.movimientos_stock_mp_v AS  SELECT m.*, ma.denom_mate
movimientos_stock_v,  CREATE VIEW movimientos_stock_v AS  SELECT m.*, a.denom_articulo nombre_articulo FROM movimientos_stock m  LEFT JOIN articulos a ON m.cod_articulo = a.cod_articulo  
mp_consumos_facon_vw,CREATE VIEW dbo.mp_consumos_facon_vw  AS  SELECT     fecha_ultima_modificacion AS fecha_movimiento, COD_MATERIAL, cod_color, - (1 * ISNULL(cantidad, 0)) AS cant, - (1 * ISNULL(cant_1, 0)) AS c1, - (1 * ISNULL(cant_2,                         0)) AS c2, - (1
mp_consumos_vw,CREATE VIEW dbo.mp_consumos_vw  AS  SELECT     dbo.Tareas_detalle.fecha_salida_real AS fecha_movimiento, dbo.Consumos_tarea.cod_material, dbo.Consumos_tarea.cod_color,                         - (1 * ISNULL(dbo.Consumos_tarea.cant_consumo, 0)) AS Cant, - (1
mp_mov_extraor_vw,CREATE VIEW dbo.mp_mov_extraor_vw  AS  SELECT     fecha_movimiento, cod_material, cod_color_material AS cod_color, (CASE WHEN efecto_movimiento = 'S' THEN - 1 ELSE 1 END) * ISNULL(cantidad, 0)                         AS cantidad, (CASE WHEN efecto_movimien
mp_remitos_vw,/*SELECT     dbo.Remitos_proveedor_cabecera.fecha_recepcion AS fecha_movimiento, dbo.remitos_proveedor_detalle.cod_material, dbo.remitos_proveedor_detalle.cod_color,                         ISNULL(dbo.remitos_proveedor_detalle.cantidad, 0) * dbo.materiales
mp_stock_agrupado_vw,CREATE VIEW mp_stock_agrupado_vw AS SELECT cod_material, cod_color_material AS cod_color, SUM(CASE WHEN efecto_movimiento = 'e' THEN cantidad ELSE (- 1 * cantidad) END) AS cant, SUM(cant_1) AS c1, SUM(cant_2) AS c2, SUM(cant_3) AS c3, SUM(cant_4) AS c4, SU
mp_stock_detallado_vw,CREATE VIEW mp_stock_detallado_vw AS SELECT fecha_ultima_modificacion AS fecha_movimiento, COD_MATERIAL, cod_color, - (1 * cantidad) AS cant, - (1 * cant_1) AS c1, - (1 * cant_2) AS c2, - (1 * cant_3) AS c3, - (1 * cant_4) AS c4, - (1 * cant_5) AS c5, - (1
mundial,  CREATE VIEW mundial AS  SELECT j.id, j.nombre, ISNULL(puntaje, 0) puntaje FROM (   SELECT    j.id jugador,    SUM((CASE WHEN pj.goles_1 = p.goles_1 AND pj.goles_2 = p.goles_2 THEN     3    ELSE     (CASE WHEN (pj.goles_1 > pj.goles_2 AND p.goles_1 > p.go
mundial_detalle,  CREATE VIEW mundial_detalle AS  SELECT    pj.id_jugador, j.nombre nombre_jugador, p.id id_partido, p.nombre nombre_partido, pj.goles_1, pj.goles_2,   (CASE WHEN p.goles_1 IS NOT NULL AND p.goles_2 IS NOT NULL THEN 1 ELSE 0 END) jugado,   (CASE WHEN pj.go
notificaciones_por_usuario_v,--Es porque la clase NotificacionPorUsuario Usuario y necesita todos sus campos para el fill  --Y además es para que aparezca la fecha y así poder filtrar en el getListObject    CREATE VIEW notificaciones_por_usuario_v AS  SELECT   a.cod_notificacion, a.vi
operadores_v,  CREATE VIEW operadores_v AS   SELECT  p.cod_personal, p.legajo_nro, p.cod_categoria, p.apellido, p.nombres, p.fecha_ultima_modificacion, p.autor_ultima_modificacion, p.anulado, p.funcion, p.cuil,       p.fecha_antiguedad_gremio, p.fecha_ingreso, p.centro
ordenes_compra_cabecera_v,  CREATE VIEW ordenes_compra_cabecera_v AS   SELECT  c.*, (SELECT SUM(cantidad_pendiente) FROM ordenes_compra_detalle d WHERE c.cod_orden_de_compra = d.cod_orden_de_compra) pendiente   FROM  ordenes_compra_cabecera c
Ordenes_compra_detalle_v,      CREATE VIEW Ordenes_compra_detalle_v AS   SELECT d.*, c.cod_proveedor, c.fecha_emision, c.es_hexagono   FROM Ordenes_compra_cabecera c   INNER JOIN Ordenes_compra_detalle d ON c.cod_sucursal = d.cod_sucursal AND c.nro_orden_compra = d.nro_orden_compr
patrones_se_vigentes_v,CREATE VIEW dbo.patrones_se_vigentes_v  AS  SELECT     TOP 100 PERCENT dbo.Patrones_mp_detalle.cod_seccion, dbo.Patrones_mp_cabecera.cod_articulo, dbo.articulos.denom_articulo,                         dbo.Patrones_mp_detalle.cod_color_articulo, dbo.Patrone
patrones_v,CREATE VIEW dbo.patrones_v  AS  SELECT     dbo.Patrones_mp_cabecera.cod_color_articulo, dbo.articulos.denom_articulo, dbo.Patrones_mp_cabecera.cod_articulo,                         dbo.Patrones_mp_cabecera.version, dbo.Patrones_mp_detalle.cod_material, dbo
patrones_vigentes_v,CREATE VIEW dbo.patrones_vigentes_v  AS  SELECT     TOP 100 PERCENT dbo.Patrones_mp_detalle.cod_seccion, dbo.Patrones_mp_cabecera.cod_articulo, dbo.articulos.denom_articulo,                         dbo.Patrones_mp_detalle.cod_color_articulo, dbo.Patrones_m
pedidos_clientes_articulo_vendedor,CREATE VIEW dbo.pedidos_clientes_articulo_vendedor  AS  SELECT     TOP 100 PERCENT dbo.pedidos_d.cod_articulo, dbo.pedidos_d.cod_color_articulo, dbo.pedidos_d.pendiente, dbo.pedidos_d.cantidad AS Pedido,                         dbo.pedidos_d.pend_1 AS P1, 
pedidos_clientes_sin_mora_vw,CREATE VIEW dbo.pedidos_clientes_sin_mora_vw  AS  SELECT     TOP 100 PERCENT dbo.pedidos_detalle.cod_articulo, dbo.pedidos_detalle.cod_color_articulo, SUM(dbo.pedidos_detalle.cantidad_pendiente)                         AS Pendiente, SUM(dbo.pedidos_detalle
pedidos_d_v,CREATE VIEW dbo.pedidos_d_v  AS  SELECT     a.*, b.cod_cliente AS cod_cliente, cl.cod_vendedor AS cod_vendedor, b.aprobado AS aprobado, b.fecha_alta AS fecha_pedido,                         p.predespachados AS predespachados, p.pred_1 AS pred_1, p.pred_2 A
Pedidos_rentabilidad_v,CREATE VIEW dbo.Pedidos_rentabilidad_v  AS  SELECT     p.nro_pedido AS nro_pedido, p.cod_articulo, dbo.costo_producto_total_V.denom_articulo, p.cod_color_articulo, p.cantidad, p.precio_unitario,                         dbo.costo_producto_total_V.cod_linea,
pendientes_aplicacion_clientes_v,CREATE VIEW [dbo].[pendientes_aplicacion_clientes_v] AS   SELECT d.cod_cliente, c.razon_social, d.empresa, d.fecha_documento,     dbo.sumarTiempo(d.fecha_documento, 'dia', 60) fecha_vencimiento,     d.tipo_docum, d.letra, d.nro_documento, d.observaciones, 
permisos_por_usuarios_por_caja_v,CREATE VIEW [dbo].[permisos_por_usuarios_por_caja_v] AS   SELECT  c.cod_caja, c.nombre, c.anulado, p.cod_usuario,p.cod_permiso,      (CASE WHEN (SELECT count(*) FROM cuenta_bancaria cb WHERE cb.cod_caja = c.cod_caja) > 0 THEN 'S' ELSE 'N' END) es_caja_banc
predespachos_v,  --Es para tener cliente y sucursal en los getListObject  CREATE VIEW predespachos_v AS   SELECT   pre.empresa empresa,   pre.nro_pedido nro_pedido,   pre.nro_item nro_item,   pe.anulado anulado,   pec.cod_ecommerce_order cod_ecommerce_order,   pec.cod_cl
presentismo,  CREATE VIEW presentismo AS    SELECT TOP 100 PERCENT t1.fecha, t1.legajo_nro, (CASE WHEN t2.legajo_nro IS NULL THEN 'AUSENTE' ELSE 'PRESENTE' END) presencia  FROM (   SELECT dias.*, p.legajo_nro   FROM (    SELECT fecha    FROM registro_entradas_salidas 
prestashop_articulos_update_v,CREATE VIEW dbo.prestashop_articulos_update_v  AS  SELECT     TOP 100 PERCENT (CASE ecommerce_forsale WHEN 'S' THEN (1) ELSE 0 END) AS [On Sale], 0 AS [Online Only], '' AS EAN13, '' AS UPC, 0 AS [Eco-Tax],                         (CASE [stock_01_14_20_por_
prestashop_imagenes_update,CREATE VIEW dbo.prestashop_imagenes_update  AS  SELECT     cpa.cod_articulo, cpa.cod_color_articulo,                            (SELECT     imagen                              FROM          dbo.articulos_imagenes AS ai                              WHERE   
programacion_empaque_v,CREATE VIEW dbo.programacion_empaque_v  AS  SELECT     dbo.Orden_fabricacion.Confirmada, dbo.Orden_fabricacion.fecha_inicio, dbo.Tareas_cabecera.fecha_corte, dbo.Tareas_cabecera.fecha_aparado,                         dbo.Tareas_cabecera.fecha_armado, dbo.T
promedio_tolerancia_pagados,  CREATE VIEW promedio_tolerancia_pagados  AS  SELECT    casiPagas.documento_fecha,   casiPagas.cod_cli,   casiPagas.empresa,   casiPagas.factura_nro,   casiPagas.letra_factura,   promedioHijas.promedio  FROM  (   SELECT    facturasNuevas.documento_fecha, 
proveedor_v,    CREATE VIEW [dbo].[proveedor_v] AS   SELECT p.cod_prov, p.tipo_proveedor, p.fecha_baja, p.vivo, p.razon_social, p.denom_fantasia, p.cuit, p.condicion_iva, p.rubro, p.imputacion_en_compra, p.calle, p.numero,     p.piso, p.oficina_depto, p.cod_postal, p.
proveedores_materias_primas_v,CREATE VIEW proveedores_materias_primas_v AS   SELECT pmp.*, m.denom_material   FROM proveedores_materias_primas pmp   INNER JOIN materiales m ON m.cod_material = pmp.cod_material    
proveedores_plazo_pago,  CREATE VIEW proveedores_plazo_pago AS  SELECT   cod_prov AS Cod,   razon_social AS Razon_Social,   denom_fantasia AS Denom_Fantasia,   plazo_pago AS Plazo_Pago  FROM proveedores_datos  WHERE anulado = 'N'
proveedores_v,  CREATE VIEW [dbo].[proveedores_v] AS   SELECT p.*, ia.importe_acumulado_mes, ia.importe_retenido_mes, gp1.saldo saldo_1, gp2.saldo saldo_2, (gp1.saldo + gp2.saldo) saldo   FROM dbo.proveedores_datos AS p    LEFT JOIN dbo.importes_op_acumulado_mes AS ia O
remitos_c_v,CREATE VIEW remitos_c_v AS   SELECT   r.*,   c.razon_social  FROM   remitos_c r  INNER JOIN clientes c ON c.cod_cli = r.cod_cliente  
reporte_articulos_v,CREATE VIEW [dbo].[reporte_articulos_v] AS  SELECT     dbo.documentos_c.cod_cliente, dbo.Clientes.razon_social, dbo.articulos.denom_articulo, dbo.documentos_cantidades.cod_articulo,                         dbo.documentos_cantidades.cod_color_articulo, dbo.
reporte_facturacion_proveedores_v,CREATE VIEW [dbo].[reporte_facturacion_proveedores_v] AS   SELECT    dpc.fecha, dpc.fecha_periodo_fiscal, dpc.tipo_docum, dpc.punto_venta, dpc.nro_documento, dpc.letra,    p.cod_prov, p.razon_social, p.imputacion_general, pc.denominacion denominacion_imp_g
reporte_facturacion_v,  CREATE VIEW [dbo].[reporte_facturacion_v] AS   SELECT    c.empresa, c.fecha_documento fecha, c.tipo_docum tipo_documento,    (CASE WHEN c.nro_comprobante IS NULL THEN c.nro_documento ELSE c.nro_comprobante END) numero,    c.letra letra, c.cod_cliente, cl
resumen_bancario_v,CREATE VIEW resumen_bancario_v AS   SELECT 'E' tipo, 'DC' tipo_documento, dc.cod_acreditar_debitar_cheque numero,    'Cheque Nº: ' + cast((SELECT TOP 1 c.numero    FROM cheque c    INNER JOIN importe_por_operacion_d ipod2 ON ipod2.cod_importe_operacion = i
retenciones_efectuadas_v,CREATE VIEW retenciones_efectuadas_v AS  SELECT   r.fecha, r.nombre razon_social, r.cuit, r.importe importe_retencion, o.nro_orden_de_pago, o.importe_total importe_orden_de_pago  FROM retencion_efectuada r  LEFT JOIN importe_por_operacion_d ixo ON ixo.tipo
roles_por_tipo_notificacion_v,  CREATE VIEW roles_por_tipo_notificacion_v AS  SELECT a.cod_tipo_notificacion, a.eliminable, b.*  FROM roles_por_tipo_notificacion a  INNER JOIN roles b ON a.cod_rol = b.cod_rol
roles_por_usuario_v,  --View para no hacer un JOIN en el mapper  CREATE VIEW roles_por_usuario_v AS  SELECT rpu.cod_usuario cod_usuario, r.cod_rol cod_rol, r.nombre nombre, r.tipo tipo, r.anulado anulado  FROM roles_por_usuario rpu   INNER JOIN roles r ON rpu.cod_rol = r.cod_
saldos_historicos_proveedor,  CREATE VIEW saldos_historicos_proveedor  AS  (   SELECT empresa, cod_prov, (sum(importe_debe - importe_haber)) saldo    FROM cuenta_corriente_historica_proveedor   GROUP BY empresa, cod_prov  )
stock_01_14_20_por_talle_v,CREATE VIEW dbo.stock_01_14_20_por_talle_v  AS  SELECT     TOP 100 PERCENT cod_articulo, cod_color_articulo, Talle, cantidad, cant_1  FROM         (SELECT     dbo.articulos.cod_articulo, dbo.colores_por_articulo.cod_color_articulo, ISNULL(stock_consolidado
stock_asignados,CREATE VIEW dbo.stock_asignados  AS  SELECT     TOP 100 PERCENT dbo.asignacion_pedidos.nro_plan, dbo.asignacion_pedidos.nro_orden_fabricacion, dbo.asignacion_pedidos.nro_tarea,                         dbo.asignacion_pedidos.cod_articulo, dbo.asignacion_ped
stock_comprometido_mp_v,CREATE VIEW dbo.stock_comprometido_mp_v  AS  SELECT     TOP 100 PERCENT dbo.Patrones_mp_detalle.cod_material, dbo.Patrones_mp_detalle.cod_color_material,                         SUM(ISNULL(dbo.Patrones_mp_detalle.consumo_par, 0) * ISNULL(dbo.tareas_incumpl
stock_disponible_total_v,CREATE VIEW dbo.stock_disponible_total_v  AS  SELECT     TOP 100 PERCENT dbo.colores_por_articulo.cod_articulo, dbo.articulos.denom_articulo, dbo.colores_por_articulo.cod_color_articulo,                         dbo.colores_por_articulo.id_tipo_producto_sto
stock_menos_asignado_vw,CREATE VIEW dbo.stock_menos_asignado_vw  AS  SELECT     cod_almacen, cod_articulo, cod_color_articulo, SUM(cant_s) AS cant_s, SUM(S1) AS S1, SUM(S2) AS S2, SUM(S3) AS S3, SUM(S4) AS S4, SUM(S5)                         AS S5, SUM(S6) AS S6, SUM(S7) AS S7, S
stock_menos_pendiente_vw,CREATE VIEW dbo.stock_menos_pendiente_vw  AS  SELECT     stock_d.cod_almacen, stock_d.cod_articulo, stock_d.cod_color_articulo, SUM(stock_d.cant_s) AS cant_s, SUM(stock_d.S1) AS S1, SUM(stock_d.S2)                         AS S2, SUM(stock_d.S3) AS S3, SUM(
stock_menos_pendiente_vw_original,CREATE VIEW dbo.stock_menos_pendiente_vw_original AS SELECT stock_d.cod_almacen, stock_d.cod_articulo, stock_d.cod_color_articulo, SUM(stock_d.cant_s) AS cant_s, SUM(stock_d.S1) AS S1, SUM(stock_d.S2) AS S2, SUM(stock_d.S3) AS S3, SUM(stock_d.S4) AS S4, SU
stock_mp,CREATE VIEW dbo.stock_mp  AS  SELECT     TOP 100 PERCENT dbo.Materias_primas.cod_material, dbo.materiales.denom_material, dbo.Materias_primas.cod_color, a.cod_almacen, SUM(a.cant)                         AS cant, SUM(a.c1) AS c1, SUM(a.c2) AS c2, SUM(a.c3)
stock_mp_detalle,CREATE VIEW dbo.stock_mp_detalle  AS  SELECT     TOP 100 PERCENT fecha_movimiento, cod_material, cod_color, cantidad, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, cod_almacen, Motivo, nro_operacion,                         efecto_movimiento  FROM         (SELE
stock_mp_rango,CREATE VIEW stock_mp_rango AS SELECT TOP 100 PERCENT cod_material, cod_color, SUM(cant) AS cant, SUM(c1) AS c1, SUM(c2) AS c2, SUM(c3) AS c3, SUM(c4) AS c4, SUM(c5) AS c5, SUM(c6) AS c6, SUM(c7) AS c7, SUM(c8) AS c8, SUM(c9) AS c9, SUM(c10) AS c10 FROM (SE
stock_mp_sin_rango_ a_eliminar,CREATE VIEW [dbo].[stock_mp_sin_rango] AS   SELECT TOP 100 PERCENT cod_material, cod_color, SUM(cant) AS cant FROM   (SELECT dbo.materias_primas_movim_extraor.cod_material, dbo.materias_primas_movim_extraor.cod_color_material AS cod_color, SUM(- dbo.materi
stock_mp_vw,  CREATE VIEW dbo.stock_mp_vw AS  SELECT s.cod_almacen, s.cod_material, s.cod_color,    ISNULL(s.cant_1, 0) AS S1,    ISNULL(s.cant_2, 0) AS S2,    ISNULL(s.cant_3, 0) AS S3,    ISNULL(s.cant_4, 0) AS S4,    ISNULL(s.cant_5, 0) AS S5,    ISNULL(s.cant_6, 0
stock_pedidos_pendientes,CREATE VIEW dbo.stock_pedidos_pendientes  AS  SELECT     TOP 100 PERCENT dbo.pedidos_d.cod_almacen, dbo.pedidos_d.cod_articulo, dbo.pedidos_d.cod_color_articulo, SUM(ISNULL(dbo.pedidos_d.pend_1,                         CONVERT(numeric, 0))) AS pend_1, SUM(
stock_pedidos_pendientes_cliente_v,CREATE VIEW dbo.stock_pedidos_pendientes_cliente_v  AS  SELECT     TOP 100 PERCENT dbo.pedidos_c.cod_cliente, dbo.pedidos_d.cod_almacen, dbo.pedidos_d.cod_articulo, dbo.pedidos_d.cod_color_articulo,                         SUM(ISNULL(dbo.pedidos_d.pend_1, 
stock_pedidos_pendientes_con_estado_v,CREATE VIEW dbo.stock_pedidos_pendientes_con_estado_v  AS  SELECT     TOP 100 PERCENT dbo.pedidos_d.cod_articulo, dbo.pedidos_d.cod_color_articulo, SUM(dbo.pedidos_d.pendiente) AS cant_pend,                         SUM(dbo.pedidos_d.pend_1) AS pend_1, SUM(
stock_pedidos_predespachados,  /*Stock pedidos asignados sin detalle    */  CREATE   VIEW [dbo].[stock_pedidos_predespachados]   AS  SELECT     TOP 100 PERCENT pre.cod_almacen, pre.cod_articulo, pre.cod_color_articulo, SUM(ISNULL(pre.pred_1, 0)) AS a1, SUM(ISNULL(pre.pred_2, 0)) AS a2
stock_pedidos_sin_predespachar,/*Stock pedidos que no fueron predespachados*/  CREATE VIEW dbo.stock_pedidos_sin_predespachar  AS  SELECT     TOP 100 PERCENT dbo.pedidos_d.cod_almacen, dbo.pedidos_d.cod_articulo, dbo.pedidos_d.cod_color_articulo, SUM(ISNULL(dbo.pedidos_d.pend_1,        
stock_produccion_incumplida_v,CREATE VIEW dbo.stock_produccion_incumplida_v  AS  SELECT     TOP 100 PERCENT cod_articulo, denom_articulo, cod_color_articulo, SUM(cantidad) AS cantidad, SUM(ISNULL(pos_1_cant, 0)) AS cant_1,                         SUM(ISNULL(pos_2_cant, 0)) AS cant_2, S
stock_pt,CREATE VIEW dbo.stock_pt  AS  SELECT     s.cod_almacen, s.cod_articulo, s.cod_color_articulo, ISNULL(s.cant_1, 0) AS S1, ISNULL(s.cant_2, 0) AS S2, ISNULL(s.cant_3, 0) AS S3,                         ISNULL(s.cant_4, 0) AS S4, ISNULL(s.cant_5, 0) AS S5, ISN
Stock_pt_detalle,  CREATE VIEW [dbo].[stock_pt_detalle] AS  SELECT CAST(SUBSTRING(CONVERT(VARCHAR, fecha_alta, 103), 0, 11) AS DATETIME) AS fecha_movimiento,    fecha_alta fecha_alta, cod_almacen, cod_articulo, cod_color_articulo,    (CASE tipo_movimiento WHEN 'NEG' THEN -
stock_pt_real_v,CREATE VIEW dbo.stock_pt_real_v AS select alm.cod_almacen + ' - ' + alm.denom_almacen as "Almacen",    art.cod_articulo + ' - ' + art.denom_articulo as "Articulo",    cxa.cod_color_articulo + ' - ' + cxa.denom_color as "Color",    ccu.denom_categoria as "C
Stock_pt_real_valorizado_v,CREATE VIEW dbo.Stock_pt_real_valorizado_v  AS  SELECT     TOP 100 PERCENT dbo.stock_pt.cod_almacen, dbo.stock_pt.nombre_almacen, dbo.stock_pt.cod_articulo, dbo.stock_pt.nombre_articulo,                         dbo.stock_pt.cod_color_articulo, dbo.stock_pt
stock_registros_aux_vw,  CREATE VIEW [dbo].[stock_registros_aux_vw]  AS   /*    Esta consulta trae registros de cada lugar donde se debe sacar el stock y pone uno por línea    Los asignados los trae como Almacen '01'. De donde se la llame se debe agrupar y hacer la suma.    Se u
stock01_por_talle_v,CREATE VIEW dbo.stock01_por_talle_v AS SELECT dbo.articulos.cod_articulo, dbo.colores_por_articulo.cod_color_articulo, ISNULL(stock01.cantidad, 0) AS cantidad, dbo.rango_talles.posic_1 AS Talle, ISNULL(stock01.cant_1, 0) AS cant_1 FROM dbo.rango_talles INN
stock14_por_talle_v,CREATE VIEW dbo.stock14_por_talle_v  AS  SELECT     dbo.articulos.cod_articulo, dbo.colores_por_articulo.cod_color_articulo, ISNULL(stock14.cantidad, 0) AS cantidad, dbo.rango_talles.posic_1 AS Talle,                         ISNULL(stock14.cant_1, 0) AS ca
stock14y20_por_talle_v,CREATE VIEW dbo.stock14y20_por_talle_v  AS  SELECT     dbo.articulos.cod_articulo, dbo.colores_por_articulo.cod_color_articulo, ISNULL(stock14.cantidad, 0) AS cantidad, dbo.rango_talles.posic_1 AS Talle,                         ISNULL(stock14.cant_1, 0) AS
stock20_por_talle_v,CREATE VIEW dbo.stock20_por_talle  AS  SELECT     dbo.articulos.cod_articulo, dbo.colores_por_articulo.cod_color_articulo, ISNULL(stock20.cantidad, 0) AS cantidad, dbo.rango_talles.posic_1 AS Talle,                         ISNULL(stock20.cant_1, 0) AS cant
subdiario_de_ingresos_v,CREATE VIEW [dbo].[subdiario_de_ingresos_v] AS   SELECT *, total - efectivo - transferencias - retenciones AS cheques FROM ( --Calculamos los cheques así para que la consulta sea más rápida, 10 segundos contra 13    SELECT r.nro_recibo numero, r.empresa, (
sucursales_v,CREATE VIEW sucursales_v AS   SELECT s.*, l.cod_zona_geo  FROM sucursales_clientes s  LEFT JOIN localidades l ON s.cod_pais = l.cod_pais AND s.cod_provincia = l.cod_provincia AND s.cod_localidad_nro = l.cod_localidad_nro    
tareas_cabecera_v,CREATE VIEW tareas_cabecera_v AS   SELECT tc.*, o.cod_articulo, o.cod_color_articulo, o.version   FROM Tareas_cabecera tc   INNER JOIN Orden_fabricacion o ON o.nro_orden_fabricacion = tc.nro_orden_fabricacion  
tareas_detalle_v,  CREATE VIEW tareas_detalle_v AS   SELECT td.*, tc.anulado, o.cod_articulo, o.cod_color_articulo, o.version, c.vigente, a.vigente articulo_vigente, a.naturaleza   FROM Tareas_detalle td   INNER JOIN Tareas_cabecera tc ON tc.nro_orden_fabricacion = td.nro_
tareas_incumplidas_empaque_v,/*TAREAS INCUMPLIAS    */  CREATE VIEW dbo.tareas_incumplidas_empaque_v  AS  SELECT     *, nro_plan AS [plan], nro_orden_fabricacion AS op, nro_tarea AS tarea  FROM         (SELECT     TOP 100 PERCENT dbo.Orden_fabricacion.nro_plan, dbo.Orden_fabricacion.n
tareas_incumplidas_v,/*TAREAS INCUMPLIAS*/  CREATE VIEW dbo.tareas_incumplidas_v  AS  SELECT     TOP 100 PERCENT dbo.Orden_fabricacion.nro_plan, dbo.Orden_fabricacion.nro_orden_fabricacion, dbo.Tareas_detalle.nro_tarea,                         dbo.Tareas_cabecera.cantidad, dbo
tareas_sin empaque_v,CREATE VIEW dbo.[tareas_sin empaque_v]  AS  SELECT     TOP 100 PERCENT *  FROM         (SELECT     TOP 100 PERCENT dbo.Orden_fabricacion.nro_plan, dbo.Orden_fabricacion.nro_orden_fabricacion, dbo.Tareas_detalle.nro_tarea,                                   
tranferencias_materias_primas_v,CREATE VIEW dbo.tranferencias_materias_primas_v  AS  SELECT     TOP 100 PERCENT fecha_alta AS fecha_Movimiento, cod_material, cod_color, cantidad, cant_1, cant_2, cant_3, cant_4, cant_5, cant_6, cant_7, cant_8,                         cant_9, cant_10, cod_
ultimos_precios_mp,CREATE VIEW dbo.ultimos_precios_mp  AS  SELECT     d.cod_material, d.cod_color,                            (SELECT     TOP 1 ISNULL(d2.precio_unitario, 0)                              FROM          Ordenes_compra_detalle d2                              WHE
usuarios_por_almacen_v,      --Es porque la clase UsuarioPorAlmacen hereda de Usuario y necesita todos sus campos para el fill    CREATE VIEW usuarios_por_almacen_v AS  SELECT a.cod_almacen, b.*  FROM usuarios_por_almacen a  INNER JOIN users b ON a.cod_usuario = b.cod_usuario
usuarios_por_area_empresa_v,  CREATE VIEW usuarios_por_area_empresa_v AS   SELECT a.id_area_empresa, b.*   FROM usuarios_por_area_empresa a   INNER JOIN users b ON a.cod_usuario = b.cod_usuario
usuarios_por_caja_v,      CREATE VIEW [dbo].[usuarios_por_caja_v] AS   SELECT  c.cod_caja, c.nombre, p.cod_usuario,      (CASE WHEN (SELECT count(*) FROM cuenta_bancaria cb WHERE cb.cod_caja = c.cod_caja) > 0 THEN 'S' ELSE 'N' END) es_caja_banco   FROM  usuarios_por_caja p IN
usuarios_por_seccion_v,  CREATE VIEW [dbo].[usuarios_por_seccion_v] AS  SELECT a.cod_seccion, b.*  FROM usuarios_por_seccion a  INNER JOIN users b ON a.cod_usuario = b.cod_usuario
usuarios_por_tipo_notificacion_v,  CREATE VIEW usuarios_por_tipo_notificacion_v AS    SELECT a.cod_tipo_notificacion, a.eliminable, b.*  FROM usuarios_por_tipo_notificacion a  INNER JOIN users b ON a.cod_usuario = b.cod_usuario
valores_en_cartera_v,  CREATE VIEW valores_en_cartera_v AS  SELECT TOP 100 PERCENT c.cod_cheque, c.empresa, c.numero, banco.nombre banco_nombre, c.importe, c.fecha_vencimiento, c.cod_cliente, cl.razon_social, c.librador_nombre, c.librador_cuit, c.dias_vencimiento AS dias  FROM
view_prueba_v,
VIEW1,CREATE VIEW dbo.VIEW1  AS  SELECT     situacion, cod_seccion, cod_articulo, denom_articulo, cod_color_articulo, SUM(cantidad) AS cant  FROM         dbo.tareas_incumplidas_v  GROUP BY situacion, cod_seccion, cod_articulo, denom_articulo, cod_color_articulo 
VIEW2,CREATE VIEW dbo.VIEW2  AS  SELECT     TOP 100 PERCENT empresa, 1 AS punto_venta, 'REC' AS tipo_docum, nro_recibo AS numero, 'R' AS letra, nro_recibo AS nro_comprobante,                         anulado, NULL AS tipo_docum_2, dbo.IfNullZero(cod_cliente) AS c
VIEW3,CREATE VIEW dbo.VIEW3  AS  SELECT     TOP 100 PERCENT dbo.colores_por_articulo.catalogo_orden_pagina AS [Position], 'Spiral' AS Manufacturer, '' AS Supplier,                         dbo.colores_por_articulo.cod_articulo + dbo.colores_por_articulo.cod_color
