

SET @schema := 'koi1_stage';


SELECT c.view_name AS missing_view
FROM (
SELECT 'Marcas' AS view_name UNION ALL
SELECT 'Ordenes_compra_detalle_v' AS view_name UNION ALL
SELECT 'Pedidos_rentabilidad_v' AS view_name UNION ALL
SELECT 'Stock_pt_detalle' AS view_name UNION ALL
SELECT 'Stock_pt_real_valorizado_v' AS view_name UNION ALL
SELECT 'almacenes_por_seccion_v' AS view_name UNION ALL
SELECT 'articulos_imagenes_v' AS view_name UNION ALL
SELECT 'asignados_por_tarea' AS view_name UNION ALL
SELECT 'banco_propio_v' AS view_name UNION ALL
SELECT 'caja_v' AS view_name UNION ALL
SELECT 'cajas_posibles_transferencia_interna_v' AS view_name UNION ALL
SELECT 'cajas_resumen' AS view_name UNION ALL
SELECT 'cheque_v' AS view_name UNION ALL
SELECT 'chequera_v' AS view_name UNION ALL
SELECT 'cheques_propios_v' AS view_name UNION ALL
SELECT 'cheques_rechazados_v' AS view_name UNION ALL
SELECT 'clientes_v' AS view_name UNION ALL
SELECT 'colores_por_articulo_v' AS view_name UNION ALL
SELECT 'compras_pendientes' AS view_name UNION ALL
SELECT 'compras_vw' AS view_name UNION ALL
SELECT 'consumos_comprometidos_v' AS view_name UNION ALL
SELECT 'costo_factura_total_v' AS view_name UNION ALL
SELECT 'costo_mp_factura_24meses_v' AS view_name UNION ALL
SELECT 'costo_mp_factura_v' AS view_name UNION ALL
SELECT 'costo_mp_producto_V' AS view_name UNION ALL
SELECT 'costo_mp_producto_detalle_v' AS view_name UNION ALL
SELECT 'costo_mp_semielaborado_detalle_v' AS view_name UNION ALL
SELECT 'costo_producto_total_V' AS view_name UNION ALL
SELECT 'costos_fijos_periodo_v' AS view_name UNION ALL
SELECT 'costos_fijos_periodo_vig_v' AS view_name UNION ALL
SELECT 'cuenta_corriente_historica' AS view_name UNION ALL
SELECT 'cuenta_corriente_historica_proveedor' AS view_name UNION ALL
SELECT 'cuenta_corriente_historica_proveedor_v' AS view_name UNION ALL
SELECT 'despachos_d_v' AS view_name UNION ALL
SELECT 'despachos_v' AS view_name UNION ALL
SELECT 'documento_proveedor' AS view_name UNION ALL
SELECT 'documento_proveedor_aplicacion_debe_v' AS view_name UNION ALL
SELECT 'documento_proveedor_aplicacion_haber_v' AS view_name UNION ALL
SELECT 'documento_proveedor_aplicacion_v' AS view_name UNION ALL
SELECT 'documento_proveedor_h_v' AS view_name UNION ALL
SELECT 'documentos' AS view_name UNION ALL
SELECT 'documentos_aplicacion_debe_v' AS view_name UNION ALL
SELECT 'documentos_aplicacion_haber_v' AS view_name UNION ALL
SELECT 'documentos_aplicacion_v' AS view_name UNION ALL
SELECT 'documentos_cantidades' AS view_name UNION ALL
SELECT 'documentos_d_v' AS view_name UNION ALL
SELECT 'documentos_h_v' AS view_name UNION ALL
SELECT 'documentos_rentabilidad' AS view_name UNION ALL
SELECT 'documentos_vendedor' AS view_name UNION ALL
SELECT 'ecomexperts_articulos_update_v' AS view_name UNION ALL
SELECT 'ecommerce_colores_por_articulo_v' AS view_name UNION ALL
SELECT 'ecommerce_orders_v' AS view_name UNION ALL
SELECT 'egreso_de_fondos_v' AS view_name UNION ALL
SELECT 'egresos_compras_gastos_vw' AS view_name UNION ALL
SELECT 'egresos_ff_vw' AS view_name UNION ALL
SELECT 'egresos_op_vw' AS view_name UNION ALL
SELECT 'egresos_vw' AS view_name UNION ALL
SELECT 'facturacion_cantidades_por_articulo_v' AS view_name UNION ALL
SELECT 'facturas_con_saldo_pendientexxx' AS view_name UNION ALL
SELECT 'facturas_detalle' AS view_name UNION ALL
SELECT 'fasonier_v' AS view_name UNION ALL
SELECT 'ficha_tecnica_patrones_d' AS view_name UNION ALL
SELECT 'fichajes_v' AS view_name UNION ALL
SELECT 'filas_asientos_contables_v' AS view_name UNION ALL
SELECT 'gastos_vw' AS view_name UNION ALL
SELECT 'gestion_proveedores' AS view_name UNION ALL
SELECT 'gestion_proveedores_1' AS view_name UNION ALL
SELECT 'gestion_proveedores_2' AS view_name UNION ALL
SELECT 'importe_por_operacion_d_v' AS view_name UNION ALL
SELECT 'importes_op_acumulado_mes' AS view_name UNION ALL
SELECT 'indicadores_por_rol_v' AS view_name UNION ALL
SELECT 'ingresos_v' AS view_name UNION ALL
SELECT 'koi_ticket_v' AS view_name UNION ALL
SELECT 'lineas_productos' AS view_name UNION ALL
SELECT 'listado_clientes_v' AS view_name UNION ALL
SELECT 'listado_proveedores_v' AS view_name UNION ALL
SELECT 'materiales_preferentes_v' AS view_name UNION ALL
SELECT 'materiales_v' AS view_name UNION ALL
SELECT 'materias_primas_v' AS view_name UNION ALL
SELECT 'movimientos_caja_v' AS view_name UNION ALL
SELECT 'movimientos_caja_v_anul' AS view_name UNION ALL
SELECT 'movimientos_caja_v_chq' AS view_name UNION ALL
SELECT 'movimientos_caja_v_noanul' AS view_name UNION ALL
SELECT 'movimientos_stock_mp_v' AS view_name UNION ALL
SELECT 'movimientos_stock_v' AS view_name UNION ALL
SELECT 'mp_consumos_facon_vw' AS view_name UNION ALL
SELECT 'mp_consumos_vw' AS view_name UNION ALL
SELECT 'mp_mov_extraor_vw' AS view_name UNION ALL
SELECT 'mp_remitos_vw' AS view_name UNION ALL
SELECT 'mp_stock_agrupado_vw' AS view_name UNION ALL
SELECT 'mp_stock_detallado_vw' AS view_name UNION ALL
SELECT 'mundial' AS view_name UNION ALL
SELECT 'mundial_detalle' AS view_name UNION ALL
SELECT 'notificaciones_por_usuario_v' AS view_name UNION ALL
SELECT 'operadores_v' AS view_name UNION ALL
SELECT 'ordenes_compra_cabecera_v' AS view_name UNION ALL
SELECT 'patrones_se_vigentes_v' AS view_name UNION ALL
SELECT 'patrones_v' AS view_name UNION ALL
SELECT 'patrones_vigentes_v' AS view_name UNION ALL
SELECT 'pedidos_clientes_articulo_vendedor' AS view_name UNION ALL
SELECT 'pedidos_clientes_sin_mora_vw' AS view_name UNION ALL
SELECT 'pedidos_d_v' AS view_name UNION ALL
SELECT 'pendientes_aplicacion_clientes_v' AS view_name UNION ALL
SELECT 'permisos_por_usuarios_por_caja_v' AS view_name UNION ALL
SELECT 'predespachos_v' AS view_name UNION ALL
SELECT 'presentismo' AS view_name UNION ALL
SELECT 'prestashop_articulos_update_v' AS view_name UNION ALL
SELECT 'prestashop_imagenes_update' AS view_name UNION ALL
SELECT 'programacion_empaque_v' AS view_name UNION ALL
SELECT 'promedio_tolerancia_pagados' AS view_name UNION ALL
SELECT 'proveedor_v' AS view_name UNION ALL
SELECT 'proveedores_materias_primas_v' AS view_name UNION ALL
SELECT 'proveedores_plazo_pago' AS view_name UNION ALL
SELECT 'proveedores_v' AS view_name UNION ALL
SELECT 'remitos_c_v' AS view_name UNION ALL
SELECT 'reporte_articulos_v' AS view_name UNION ALL
SELECT 'reporte_facturacion_proveedores_v' AS view_name UNION ALL
SELECT 'reporte_facturacion_v' AS view_name UNION ALL
SELECT 'resumen_bancario_v' AS view_name UNION ALL
SELECT 'retenciones_efectuadas_v' AS view_name UNION ALL
SELECT 'roles_por_tipo_notificacion_v' AS view_name UNION ALL
SELECT 'roles_por_usuario_v' AS view_name UNION ALL
SELECT 'saldos_historicos_proveedor' AS view_name UNION ALL
SELECT 'stock01_por_talle_v' AS view_name UNION ALL
SELECT 'stock14_por_talle_v' AS view_name UNION ALL
SELECT 'stock14y20_por_talle_v' AS view_name UNION ALL
SELECT 'stock20_por_talle_v' AS view_name UNION ALL
SELECT 'stock_01_14_20_por_talle_v' AS view_name UNION ALL
SELECT 'stock_asignados' AS view_name UNION ALL
SELECT 'stock_comprometido_mp_v' AS view_name UNION ALL
SELECT 'stock_disponible_total_v' AS view_name UNION ALL
SELECT 'stock_menos_asignado_vw' AS view_name UNION ALL
SELECT 'stock_menos_pendiente_vw' AS view_name UNION ALL
SELECT 'stock_menos_pendiente_vw_original' AS view_name UNION ALL
SELECT 'stock_mp' AS view_name UNION ALL
SELECT 'stock_mp_detalle' AS view_name UNION ALL
SELECT 'stock_mp_rango' AS view_name UNION ALL
SELECT 'stock_mp_sin_rango_ a_eliminar' AS view_name UNION ALL
SELECT 'stock_mp_vw' AS view_name UNION ALL
SELECT 'stock_pedidos_pendientes' AS view_name UNION ALL
SELECT 'stock_pedidos_pendientes_cliente_v' AS view_name UNION ALL
SELECT 'stock_pedidos_pendientes_con_estado_v' AS view_name UNION ALL
SELECT 'stock_pedidos_predespachados' AS view_name UNION ALL
SELECT 'stock_pedidos_sin_predespachar' AS view_name UNION ALL
SELECT 'stock_produccion_incumplida_v' AS view_name UNION ALL
SELECT 'stock_pt' AS view_name UNION ALL
SELECT 'stock_pt_real_v' AS view_name UNION ALL
SELECT 'stock_registros_aux_vw' AS view_name UNION ALL
SELECT 'subdiario_de_ingresos_v' AS view_name UNION ALL
SELECT 'sucursales_v' AS view_name UNION ALL
SELECT 'sysconstraints' AS view_name UNION ALL
SELECT 'syssegments' AS view_name UNION ALL
SELECT 'tareas_cabecera_v' AS view_name UNION ALL
SELECT 'tareas_detalle_v' AS view_name UNION ALL
SELECT 'tareas_incumplidas_empaque_v' AS view_name UNION ALL
SELECT 'tareas_incumplidas_v' AS view_name UNION ALL
SELECT 'tareas_sin empaque_v' AS view_name UNION ALL
SELECT 'tranferencias_materias_primas_v' AS view_name UNION ALL
SELECT 'ultimos_precios_mp' AS view_name UNION ALL
SELECT 'usuarios_por_almacen_v' AS view_name UNION ALL
SELECT 'usuarios_por_area_empresa_v' AS view_name UNION ALL
SELECT 'usuarios_por_caja_v' AS view_name UNION ALL
SELECT 'usuarios_por_seccion_v' AS view_name UNION ALL
SELECT 'usuarios_por_tipo_notificacion_v' AS view_name UNION ALL
SELECT 'valores_en_cartera_v' AS view_name UNION ALL
SELECT 'view_prueba_v' AS view_name
) AS c
LEFT JOIN information_schema.VIEWS v
  ON v.TABLE_SCHEMA = @schema AND BINARY v.TABLE_NAME = c.view_name
WHERE v.TABLE_NAME IS NULL
ORDER BY c.view_name;
